apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: database.example.org/v1alpha1
kind: CompositePostgreSQLInstance
metadata:
  name: my-db-instance
  namespace: demo
spec:
  parameters:
    storageGB: 10
    #finalDBSnapshot: my-db-instance-dido
    # Possible values small, medium, large
    dbInstance: small
    deletionProtection: false
  compositionSelector:
    matchLabels:
      provider: aws-provider
  writeConnectionSecretToRef:
    name: my-db-instance
    namespace: demo
