apiVersion: ec2.aws.crossplane.io/v1beta1 
kind: VPC
metadata:
  name: example-vpc
  annotations:
    crossplane.io/external-name: vpc-004901d621f04924b
spec:
  forProvider:
    region: eu-west-1
    cidrBlock: 10.0.0.0/16
  providerConfigRef:
    name: aws-provider

